---
- name: Create Jenkins namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: jenkins
    state: present
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy Jenkins 
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-deployment.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"

 

- name: Expose Jenkins service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-service.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy serviceaccount 
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-serviceaccount.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy jenkins clusterrole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-role.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy jenkins clusterrolebinding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-rolebinding.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"