---
- name: Add Jenkins Helm repo
  community.kubernetes.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: Update Helm repo
  ansible.builtin.command: helm repo update
  register: helm_update
  changed_when: "'Update Complete' in helm_update.stdout"

- name: Create Jenkins namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: jenkins
    state: present
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy Jenkins via Helm 
  community.kubernetes.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: jenkins
    kubeconfig: "{{ kubeconfig_path }}"
    create_namespace: false
    values:
      controller:
        admin:
          username: "{{ jenkins_admin_user }}"
          password: "{{ jenkins_admin_password }}"
    wait: true
    state: present

- name: Expose Jenkins service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins-service.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_path }}"